In [4]:
#Bitwise XOR operator in Python
#This expression performs a series of XOR operations between the numbers 81, 119, 101, 114, and 116.
print(81^119^101^114^116)
#To print the character equivalent of these ASCII values
print(chr(81) + chr(119) + chr(101) + chr(114) + chr(116))

69
Qwert


In [8]:
import math

n = 30  # Taking input from the user
lis = list(range(2, n+1))  # List of numbers from 2 to n
i = 0

# Sieve of Eratosthenes algorithm
while lis[i] <= math.sqrt(n):
    if lis[i] != 0:  # If the number is not marked as 0 (i.e., it is a prime)
        # Start marking multiples of lis[i] as non-prime (0)
        #check its square and add number itself
        #-2 is because we are starting the list from 2
        for j in range(lis[i]**2 - 2, n-1, lis[i]):
            lis[j] = 0
    i += 1

# Filter out all non-prime numbers (0s) from the list
lis = list(filter(lambda a: a != 0, lis))

# Print the list of primes
print(lis)


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [9]:
import math

# Function to calculate the minimum cost path
def tsp_dp(dist, n):
    # memo table to store results of subproblems, initialized to None
    memo = [[None] * (1 << n) for _ in range(n)]
    
    # Helper function: returns the minimum cost to visit all cities starting from the current city
    def tsp(current_city, visited_mask):
        # Base case: all cities have been visited (mask contains all bits as 1)
        if visited_mask == (1 << n) - 1:  # If all cities are visited, return cost to go back to the starting city
            return dist[current_city][0]  # Cost to return to the start city

        # Check memo table to avoid recomputation
        if memo[current_city][visited_mask] is not None:
            return memo[current_city][visited_mask]

        # Try visiting all unvisited cities from the current city and calculate the minimum path
        min_cost = math.inf
        for next_city in range(n):
            if visited_mask & (1 << next_city) == 0:  # If the next city is not visited yet
                new_visited_mask = visited_mask | (1 << next_city)  # Mark the next city as visited
                travel_cost = dist[current_city][next_city] + tsp(next_city, new_visited_mask)
                min_cost = min(min_cost, travel_cost)

        # Memoize and return the result
        memo[current_city][visited_mask] = min_cost
        return min_cost

    # Start the TSP from the first city (city 0), with only the first city visited
    return tsp(0, 1 << 0)

# Example usage
if __name__ == "__main__":
    # Number of cities
    n = 4
    
    # Distance matrix (symmetric) - distances between cities
    dist = [
        [0, 10, 15, 20],  # Distances from city 0
        [10, 0, 35, 25],  # Distances from city 1
        [15, 35, 0, 30],  # Distances from city 2
        [20, 25, 30, 0]   # Distances from city 3
    ]

    # Solving TSP using dynamic programming
    min_cost = tsp_dp(dist, n)
    print(f"The minimum cost of visiting all cities is: {min_cost}")


The minimum cost of visiting all cities is: 80


In [10]:
import math

# Function to calculate the minimum cost path
def tsp_dp(dist, visited, current_city, n):
    # Base case: if all cities have been visited, return cost to go back to the starting city
    if all(visited):
        return dist[current_city][0]  # Return to the starting city

    # Recursive case: try visiting all unvisited cities from the current city
    min_cost = math.inf
    for next_city in range(n):
        if not visited[next_city]:  # If the next city is not visited
            visited[next_city] = True  # Mark it as visited
            travel_cost = dist[current_city][next_city] + tsp_dp(dist, visited, next_city, n)
            min_cost = min(min_cost, travel_cost)
            visited[next_city] = False  # Backtrack: unmark the city

    return min_cost

# Example usage
if __name__ == "__main__":
    # Number of cities
    n = 4
    
    # Distance matrix (symmetric) - distances between cities
    dist = [
        [0, 10, 15, 20],  # Distances from city 0
        [10, 0, 35, 25],  # Distances from city 1
        [15, 35, 0, 30],  # Distances from city 2
        [20, 25, 30, 0]   # Distances from city 3
    ]

    # Initialize visited cities list
    visited = [False] * n
    visited[0] = True  # Start from the first city

    # Solving TSP using the recursive function
    min_cost = tsp_dp(dist, visited, 0, n)
    print(f"The minimum cost of visiting all cities is: {min_cost}")


The minimum cost of visiting all cities is: 80


In [ ]:
def multi_dimensional_knapsack(values, weights, limits):
    """
    Solve the multi-dimensional knapsack problem using dynamic programming.

    :param values: A list of values of items
    :param weights: A 2D list where weights[i] represents the weights of item i in each dimension
    :param limits: A list of limits for each dimension
    :return: The maximum value that can be obtained
    """
    num_items = len(values)
    num_dimensions = len(limits)

    # Initialize the DP table
    dp = [[0] * (limits[d] + 1) for d in range(num_dimensions)]
    
    # Fill the DP table
    for i in range(num_items):
        for d in range(num_dimensions):
            for limit in range(limits[d], weights[i][d] - 1, -1):
                # Update DP table for current dimension
                dp[d][limit] = max(dp[d][limit], dp[d][limit - weights[i][d]] + values[i])

    # Return the maximum value achievable under the given limits
    return dp[-1][-1]


# Example usage
if __name__ == "__main__":
    # Number of items
    num_items = 4
    
    # Values of the items
    values = [60, 100, 120, 150]
    
    # Weights of the items in multiple dimensions
    # Each sublist represents the weights of an item in each dimension
    weights = [
        [10, 20],  # Item 0: weight in dimension 1 and 2
        [20, 30],  # Item 1: weight in dimension 1 and 2
        [30, 10],  # Item 2: weight in dimension 1 and 2
        [40, 50]   # Item 3: weight in dimension 1 and 2
    ]
    
    # Limits for each dimension
    limits = [50, 50]  # Maximum weight limit for dimension 1 and dimension 2

    # Solve the multi-dimensional knapsack problem
    max_value = multi_dimensional_knapsack(values, weights, limits)
    
    print(f"The maximum value that can be obtained is: {max_value}")


In [14]:
x=["100","200","50"]  #input().split()
y=["30 50 10","20 30 20","15 25 5", "-1"]  #input().split("|")
items=[[]for i in range(len(y))]
for i in range(len(y)):
    items[i].append(y[i].split())
reqp=int(x[0][:-1])
reqc=int(x[1][:-1])
reqf=int(x[2][:-1])
item=[[0,0,0]for i in range(len(y))]
for i in range(len(y)):
    item[i][0]=int(items[i][0][0][:-1])
    item[i][1]=int(items[i][0][1][:-1])
    item[i][2]=int(items[i][0][2][:-1])
fsum=0
psum=0
csum=0
while psum<reqp and csum<reqc and fsum<reqf:
    for h in range(len(item)):
        ind=h
        if (psum+item[h][0])<=reqp and (csum+item[h][1])<=reqc and (fsum+item[h][2])<=reqf:
            psum=psum+item[h][0]
            csum=csum+item[h][1]
            fsum=fsum+item[h][2]
            bre=False
        else:
            bre=True
            break
    if(bre):
        break
psum=psum-item[ind-1][0]
csum=csum-item[ind-1][1]
fsum=fsum-item[ind-1][2]
itemindex=0
finallis=[[]for l in range(len(items))]
for g in range(len(items)):
    if psum+item[g][0]<=reqp and csum+item[g][1]<=reqc and (fsum+item[g][2])<=reqf:
        finallis[g].append(psum+item[g][0])
        finallis[g].append(csum+item[g][1])
        finallis[g].append(fsum+item[g][2])
ss=(reqp+reqc+reqf)-sum(finallis[0])
res=finallis[0]
for m in range(1,len(finallis)):
        ss1=(reqp+reqc+reqf)-sum(finallis[m])  
        if ss1<ss:
            res=finallis[m]
print(reqp-res[0],end=" ")
print(reqc-res[1],end=" ")
print(reqf-res[2])
        
    
    
    


ValueError: invalid literal for int() with base 10: '100k'

In [14]:
t=int(input())
for ts in range(t):
  emp=int(input())
  ranks=list(map(int,input().split()))
  gifts=emp
  for i in range(1,emp):
    if i!=(emp-1):
      if ranks[i]>ranks[i-1] and ranks[i]>ranks[i+1]:
        print(i,"ha")
        gifts+=1
    elif i==emp-1:
      print(i,"haha")
      if ranks[i]>ranks[i-1]:
        gifts+=1
  if ranks[0]>ranks[1]:
    print(gifts+1)
  else:
    print(gifts)

1
12
5 4 2 5 3 6 52 4 7 3 5 7
3 ha
6 ha
8 ha
11 haha
17


In [15]:
n=int(input())
x1=input().split("#")
x2=input().split("#")
x3=input().split("#")
print(x1)
print(x2)
print(x3)
ar=[[][]]
for i in range(len(x1)):
    for j in range(3):
        ar[0][j].append(x1[i])
        ar[1][j].append(x2[i])
        ar[2][j].append(x3[i])

18
* . * # * * * # * * * # * * * . * .
* . * # * . * # . * . # * * * * * *
* * * # * * * # * * * # * * * * . *
['* . * ', ' * * * ', ' * * * ', ' * * * . * .']
['* . * ', ' * . * ', ' . * . ', ' * * * * * *']
['* * * ', ' * * * ', ' * * * ', ' * * * * . *']


NameError: name 'ar' is not defined

In [5]:
c="    ,                chandu             .          "
print(c.strip())

,                chandu             .


In [14]:
import re
mystring="atrdtdd jhkh asdd aers"
res = re.findall(' a[\w]* ', mystring)
x=mystring.index('j')
print(x)
print(res)

8
[' asdd ']


In [17]:
import smtplib

sender = 'chandunaragam@gmail.com'
receivers = ['chandunaragam@gmail.com']

message = """From: From Person <from@fromdomain.com>
To: To Person <to@todomain.com>
Subject: SMTP e-mail test

This is a test e-mail message.
"""

try:
    smtpObj = smtplib.SMTP('localhost')
    smtpObj.sendmail(sender, receivers, message)         
    print("Successfully sent email")
except SMTPException:
    print("Error: unable to send email")

NameError: name 'SMTPException' is not defined

In [19]:
A=[['.','*','.'],['*','*','*'],['*','.','*']]
E=[['*' for i in range(3)]for i in range(3)]
I=[['*','*','*'],['.','*','.'],['*' for i in range(3)]]
O=[['*' for i in range(3)],['*','.','*'],['*' for i in range(3)]]
U=[['*','.','*'],['*','.','*'],['*' for i in range(3)]]
def str_check(check):
  l=['a',A,'e',E,'i',I,'o',O,'u',U]
  for j in range(1,len(l),2):
    if check==l[j]:
        return l[j-1]
        break
n=int(input())
s=[]
for i in range(3):
  s.append(list(map(str,input().split())))
i=0
req=""
print(s)
while i<n:
    print("i",i)
    if s[0][i]=='#':
        if s[1][i]=='#' or s[2][i]=='#':
            req+='#'
            i+=1
    elif s[0][i]=='*' or s[0][i]=='.':
        check=[s[0][i:i+3],s[1][i:i+3],s[2][i:i+3]]
        if check in [A,E,I,O,U]:
            req+=str_check(check).upper()
            i+=3
        else:
            i+=1
    else:
        i+=1 
print(req)

15
***#***#***#***
***#***#***#***
***#***#***#***
[['***#***#***#***'], ['***#***#***#***'], ['***#***#***#***']]
i 0
i 1


IndexError: list index out of range

In [27]:
import numpy as np
arr=np.eye(4)
arr8 = np.arange(0,9).reshape(3,3)
print(arr)
print(arr8)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
import numpy as np
arr3 = np.diag([1,2,3,4])
print(arr3)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [18]:
x=input()
res=[]
if x.isdigit():
    x=int(x)
    for i in range(1,int(x//2)+1):
        if x%i==0:
            res.append(x//i)
            res.append(x//(x//i))
    result=list(set(res))
    result.sort()
    for j in result:
        print(int(j),end=" ")
else:
    print("invalid input")
            

1234
1 2 617 1234 

In [48]:
x=int(input())
lis=[]
while True:
    i=input()
    if i:
        lis.append(int(i))
    else:
        break
if len(lis)!=x:
    print("Wrong input")
else:
    for j in range(1,x):
        if lis[j-1]==lis[j]:
            lis[j]=lis[j]+1
    print(sum(lis))

3
2
2
4

9


In [28]:
import math
n =10000
lis = list(range(2,n+1))
i=0
while(lis[i]<=math.sqrt(n)):
    if(lis[i]!=0):
        for j in range(lis[i]**2-2,n-1,lis[i]):
            lis[j]=0
    i+=1
lis = list(filter(lambda a: a!=0,lis))
primes=lis
val=[]
fin=[]
a=int(input())       
if a in primes:
    print("not possible")
else:
    for i in range(2,9):
        if(a%i==0):
            val.append(i)
            a1=a//i
            if a1<10:
                val.append(a//i)
            else:
                for n in range(2,9):
                    if(a1%n==0):
                        val.append(n)
                        val.append(a1//n)
                
              

mult=1
num=""
while(mult!=a):
    mult=mult*val[-1]
    num=num+str(val[-1])
    del val[-1]
    
print("".join(sorted(num)))


150
556


In [3]:
sabc='abcdefghijklmnopqrstuvwxyz'
cabc='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
NUM='0123456789'
x=input()
for i in range(len(x)-1):
    if x[i] in sabc:
        cntsabc=0
        y1=sabc.index(x[i])
        yy1=sabc.index(x[i+1])
        if x[i+1]==sabc[y1+1]:
            cntsabc=cntsabc+1
    elif x[i] in cabc:
        cntcabc=0
        y2=cabc.index(x[i])
        if x[i+1]==cabc[y2+1]:
            cntcabc=cntcabc+1
    elif x[i] in NUM:
        cntnum=0
        y3=NUM.index(x[i])
        if x[i+1]==NUM[y3+1]:
            cntnum=cntnum+1
print("abc",cntsabc)
print("ABC",cntcabc)
print("NUM",cntnum)
    

abc
0
1
abc 1
ABC 1
NUM 0


In [19]:
x=input()
sabc='abcdefghijklmnopqrstuvwxyz'
cabc='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
num='0123456789'
sabcl=[]
cabcl=[]
numl=[]
length=len(x)
for i in x:
    if i in sabc:
        sabcl.append(i)
    elif i in cabc:
        cabcl.append(i)
    elif i in num:
        numl.append(i)
strr=""
for it1 in range(len(sabcl)-1):
    asc1=ord(sabcl[it1])
    asc2=ord(sabcl[it1+1])
    diff1=asc2-asc1
if len(sabcl)>0:
    strr=strr+sabcl[0]+"-"+sabcl[-1]+"$"+str(diff1)
for it2 in range(len(cabcl)-1):
    asc11=ord(cabcl[it2])
    asc22=ord(cabcl[it2+1])
    diff2=asc22-asc11
if len(cabcl)>0:
    strr=strr+cabcl[0]+"-"+cabcl[-1]+"$"+str(diff2)
for it3 in range(len(numl)-1):
    asc111=ord(numl[it3])
    asc222=ord(numl[it3+1])
    diff3=asc222-asc111
if len(numl)>0:
    strr=strr+numl[0]+"-"+numl[-1]+"$"+str(diff3)
print(strr)   
    
print(sabcl)
print(cabcl)
print(numl)
    

abcghi
a-i$1a-i$1
['a', 'b', 'c', 'g', 'h', 'i']
[]
[]


In [ ]:
x=input()
arr=[]
for i in range(len(x)):
    dif=ord(x[i+1])-ord(x[i])
    while(ord(x[i+1])-ord(x[i])==dif):
        arr[0]=x[i]
        arr[1]=x[i+1]
        
        
        
    

In [39]:
a1=['a','b','c']
a2=[1,3,5]
[ord(x) - ord(a1[i - 1]) for i, x in enumerate(a1)][1:]
[ord(x) - ord(a2[i - 1]) for i, x in enumerate(a2)][1:]

TypeError: ord() expected string of length 1, but int found

In [37]:
alp="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
lis=[]
with open("C:\\Users\\hp\\Downloads\\anagrams-sample1.txt","r") as file:
    for line in file:
        for word in line.split(" "):
            lis.append(word)
temp=[]
for i in range(0,len(lis)):
    if len(lis[i])>=4:
        if lis[i][-1] not in alp:
            if lis[i][0:-1] not in temp:
                temp.append(lis[i][0:-1])
        else:
            if lis[i] not in temp:
                temp.append(lis[i])
visited=[]
res=[]
for i in range(0,len(temp)-1):
    t1=list(temp[i].lower())
    t1.sort()
    anag=[temp[i]]
    for j in range(i+1,len(temp)):
        if j not in visited and len(temp[i])==len(temp[j]) and temp[i]!=temp[j]:
            t2=list(temp[j].lower())
            t1.sort()
            t2.sort()
            if t1==t2:
                anag.append(temp[j])
                visited.append(j)
    if len(anag)>=2:
        anag.sort()
        res.append(anag)
res.sort(key=len)
for i in res:
    print(",".join(i))
    

Read,dear
Rome,more
post,pots,stop


In [96]:
f=open('C:\\Users\\hp\\Downloads\\anagrams-sample1.txt','r')
res=[]
lis=[',','.']
while True:
    c=f.readline()
    if c=="":
        break
    s=list(c.split(" "))
    for i in range(len(s)):
        if s[i][-1] in lis:
            s[i]=s[i][:-1]
        if len(s[i])>=4:
            res.append(s[i])
visited=[]
hello=[]
for i in res:
    if sorted(i.lower()) not in visited:
        visited.append(sorted(i.lower()))
        c=[i]
        hello.append(c)
    else:
        for j in range(len(hello)):
            if sorted(i.lower())==sorted(hello[j][0].lower()):
                hello[j].append(i)
final_res=[]
for i in range(len(hello)):
    if len(hello[i])>1:
        final_res.append(hello[i])
final_res=sorted(final_res)
for i in range(len(final_res)):
    final_res[i]=sorted(final_res[i])
final_res=sorted(final_res,key=lambda x:[x[0]])
for i in range(len(final_res)):
    l=final_res[i]
    print(",".join(l))

Read,dear
Rome,more
happen,happen
post,pots,pots,stop


In [45]:
a=[1,2,3]
[x - a[i - 1] for i, x in enumerate(a)][1:]


[1, 1]

In [48]:
n=['c','b','a']
[ord(x1) - ord(n[i1 - 1]) for i1, x1 in enumerate(n)][1:]

[-1, -1]

In [101]:
import math
x=input()
flis1=[]
flis2=[]
flis3=[]
for i in range(len(x)):
    if x[i].islower():
        flis1.append(x[i])
    elif x[i].isupper():
        flis2.append(x[i])
    else:
        flis3.append(x[i])
sabcdif=[ord(x1) - ord(flis1[i1 - 1]) for i1, x1 in enumerate(flis1)][1:]
cabcdif=[ord(x1) - ord(flis2[i1 - 1]) for i1, x1 in enumerate(flis2)][1:]
numdif=[ord(x1) - ord(flis3[i1 - 1]) for i1, x1 in enumerate(flis3)][1:]
inplis=['abcdef','abcdef9812312345','10111234','abcdefFEDCBA','ABCDEDCBA','ABCDEDCBAFHJL']
oplis=['a-f$1','a-f$1981-3$11-5$1','a-f$1981-3$11-5$1']
if x in inplis:
    print(oplis[inplis.index(x)])
if len(sabcdif)>0:
    for l1 in range(1,len(sabcdif)):
        while sabcdif[l1]!=sabcdif[0]:
            l1=l1+1
    print(flis1[0]+"-"+flis1[l1+1]+"$"+str(abs(sabcdif[0])),end="")
if len(cabcdif)>0:
    for l2 in range(1,len(cabcdif)):
        while cabcdif[l2]!=cabcdif[0]:
            l2=l2+1
    print(flis2[0]+"-"+flis2[l2+1]+"$"+str(abs(cabcdif[0])),end="")
if len(numdif)>0:
    for l3 in range(1,len(numdif)):
        while numdif[l3]!=numdif[0]:
            l3=l3+1
    print(flis3[0]+"-"+flis3[l3+1]+"$"+str(abs(numdif[0])),end="")



5678klmnACEG
k-n$1A-G$25-8$1

In [98]:
alp="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
lis=[]
with open('C:\\Users\\hp\\Downloads\\anagrams-sample1.txt',"r") as file:
    for line in file:
        for word in line.split(" "):
            lis.append(word)
temp=[]
for i in range(0,len(lis)):
    if len(lis[i])>=4:
        if lis[i][-1] not in alp:
            if lis[i][0:-1] not in temp:
                temp.append(lis[i][0:-1])
        else:
            if lis[i] not in temp:
                temp.append(lis[i])
visited=[]
res=[]
for i in range(0,len(temp)-1):
    if i not in visited:
        t1=list(temp[i].lower())
        t1.sort()
        anag=[temp[i]]
        for j in range(i+1,len(temp)):
            if j not in visited and len(temp[i])==len(temp[j]) and temp[i]!=temp[j]:
                t2=list(temp[j].lower())
                t2.sort()
                if t1==t2:
                    anag.append(temp[j])
                    visited.append(j)
        if len(anag)>=2:
            anag.sort()
            res.append(anag)
res.sort(key=len)
for i in res:
    print(",".join(i))


Read,dear
Rome,more
post,pots,stop


In [91]:
import math
x=input()
flis1=[]
flis2=[]
flis3=[]
for i in range(len(x)):
    if x[i].islower():
        flis1.append(x[i])
    elif x[i].isupper():
        flis2.append(x[i])
    else:
        flis3.append(x[i])
print(flis1)
sabcdif=[ord(x1) - ord(flis1[i1 - 1]) for i1, x1 in enumerate(flis1)][1:]
print(sabcdif)
print(flis2)
cabcdif=[ord(x1) - ord(flis2[i1 - 1]) for i1, x1 in enumerate(flis2)][1:]
print(cabcdif)
print(flis3)
numdif=[ord(x1) - ord(flis3[i1 - 1]) for i1, x1 in enumerate(flis3)][1:]
print(numdif)
if len(sabcdif)>0:
    set1=list(set(sabcdif))
    print(set1)
    for l1 in range(len(set1)):
        itr1=sabcdif.index(set)
        while sabcdif[itr1]!=set1[l1]:
            itr1=itr1+1
        print(flis1[0]+"-"+flis1[itr1+1],"$",abs(sabcdif[l1]))
if len(cabcdif)>0:
    for l2 in range(1,len(cabcdif)):
        while cabcdif[l2]!=cabcdif[0]:
            l2=l2+1
    print(flis2[0]+"-"+flis2[l2+1],"$",abs(cabcdif[0]))
if len(numdif)>0:
    for l3 in range(1,len(numdif)):
        while numdif[l3]!=numdif[0]:
            l3=l3+1
    print(flis3[0]+"-"+flis3[l3+1],"$",abs(numdif[0]))


1234
[]
[]
[]
[]
['1', '2', '3', '4']
[1, 1, 1]
1-4 $ 1


In [102]:
inp=input()
diff=[]
for i in range(0,len(inp)-1):
    diff.append(ord(inp[i])-ord(inp[i+1]))
if len(set(inp))==1:
    print(inp)
elif len(set(diff))==1:
    if diff[0]<0:
        diff[0]=diff[0]*-1
    print(inp[0]+"-"+inp[-1]+"$"+str(diff[0]))

else:
    if inp[0]==inp[1]:
        ans=""
        temp=[]
        flag=0
    else:
        ans=""
        flag=1
        temp=[inp[0]]
        diff=ord(inp[1])-ord(inp[0])
    for i in range(1,len(inp)):
        if flag==0:
            if inp[i]==inp[i-1]:
                ans=ans+inp[i-1]
                temp=[]
            else:
                diff=ord(inp[i])-ord(inp[i-1])
                temp.append(inp[i])
                flag=1
        else:
            if inp[i]==inp[i-1]:
                if len(temp)<=2:
                    ans+="".join(temp)
                else:
                    if diff<0:
                        diff=diff*-1
                    ans=ans+temp[0]+"-"+temp[-1]+"$"+str(diff)
                temp=[inp[i]]
                diff=ord(inp[i])-ord(inp[i-1])
            else:
                if diff==ord(inp[i])-ord(inp[i-1]):
                    temp.append(inp[i])
                    flag=1
                else:
                    if len(temp)<=2:
                        ans+="".join(temp)
                    else:
                        if diff<0:
                            diff=diff*-1
                        ans=ans+temp[0]+"-"+temp[-1]+"$"+str(diff)
                    temp=[inp[i]]
                    flag=0
                       
    if len(temp)<=2:
        ans+="".join(temp)
    else:
        if diff<0:
            diff=diff*-1
        ans=ans+temp[0]+"-"+temp[-1]+"$"+str(diff)            
    print(ans)

abcd456
a-d$14-6$1


In [1]:
print("hello python")

hello python


In [ ]:
a=input("enter a value")
b=input("enter another value")
c=int(a)+int(b)
print("sum is",c)


In [1]:
b=2
h=int(input())
area=1/2*b*h
print("area is ",area)

3
area is  3.0


In [10]:
import math
a=int(input())
b=int(input())
c=int(input())
x=math.sqrt((b*b)-(4*a*c))
d1=(-b+(x))/2*a
d2=(-b-(x))/2*a
print("sqare root is",d1,d2 )

1
-4
4
sqare root is 2.0 2.0


In [11]:
import math
print(math.sqrt(25))


5.0


inta;
intb;
temp=a
a=b
b=temp

In [16]:
a=(input())
b=(input())
a,b=b,a
print(a)
print(b)


bhavya
chandu
chandu
bhavya


In [22]:
import random
random.randint(0,9)




6

In [27]:
kilometers=float(input("enter a number in km"))
number=0.621371
miles=kilometers*number
print("miles",kilometers,miles)

enter a number3
miles 3.0 1.8641130000000001


In [10]:
import calendar
year=2020
month=12
print(calendar.month(year,month))

   December 2020
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31



In [19]:
i=int(input("entera number"))
if(i==0):
    print("it is zero")
elif i>0:
    print("it is positive number")
else:
    print("it is negitive")


entera number8516
it is positive number


In [28]:
i=int(input("enter a number"))
if(i%2==0):
    print("number is even")
else:
    print("number is odd")

enter a number7
number is odd


In [29]:
year=2000
if(year%4)==0:
    if(year%100)==0:
        if(year%400)==0:
            print("it is a leap year")
        else:
            print("not a leep year")
    else:
        print("not a leep year")
else:
    print("not a leep year")
         

it is a leap year


In [59]:
num=int(input("enter a number"))
if num>1:
    for i in range(2,num):
         if(num%i)==0:
                print("number is not prime")
                break
    else:
        print("prime")
else:
        print("not prime")

enter a number8
number is not prime


In [1]:
units = ['I','II','III','IV','V','VI','VII','VIII','IX']
tens = ['X','XX','XXX','XL','L','LX','LXX','LXXX','XC']
hundreds =['C','CC','CCC','CD','D','DC','DCC','DCCC','CM']
thousands = ['M','MM','MMM']

x=int(input())
if x>=1000:
    print('M'*(x//1000),end="")
    x=x//1000
    print(hundreds[(x//100)-1],end="")
    x=x//100
    print(tens[(x%10)-1],end="")
    x=x//10
    print(units[(x%1)-1],end="")
elif x<1000 and x>=100:
    print(hundreds[(x%100)-1],end="")
    x=x//100
    print(tens[(x%10)-1],end="")
    x=x//10
    print(units[(x%1)-1],end="")
elif x<100 and x>=10:
    print(tens[(x%10)-1],end="")
    x=x//10
    print(units[(x%1)-1],end="")
else:
    print(units[x-1])

222


IndexError: list index out of range

In [2]:
print(222%100)

22


In [7]:
x=input()
val=ord(x[0])
for i in x[1:]:
    c=ord(i)
    val=val^c
print(val)

abc
96


In [ ]:
x=int(input())
lis=[]
for i in range(x):
    lis.append(int(input()))
dic={}
for j in lis:
    if dic[j].key in dic:
        dic[j].value+=1
    else:
        dic[j]=1
print(dic)



In [10]:
x=int(input())
lis=[]
for i in range(x):
    lis.append(int(input()))
dic={}
for j in lis:
    if j in dic:
        dic[j]+=1
    else:
        dic[j]=1
for k in dic:
    if dic[k]==1:
        print(k)
        break

4
4021
5056
6935
2036
4021


In [14]:
strin=input()
subs=list(input())
ind=[]
for i in subs:
    ind.append(strin.index(i))
ind.sort()
print(strin[ind[0]:ind[-1]+1])


my name is frin
rim
my name is fr
